# Generated by Django 5.1.4 on 2025-02-10 03:32

import url_shortner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(unique=True)),
                ('short_code', models.CharField(default=url_shortner.models.generate_short_code, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.IntegerField(default=0)),
            ],
        ),
    ]
