# Generated by Django 5.1.4 on 2025-02-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_shorturl_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
