# Generated by Django 5.1.4 on 2025-02-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0003_shorturl_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.URLField(),
        ),
    ]
